name: "GitHub Actions Shell"
run-name: $ ${{ inputs.command }}
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'The command to run'
        required: true
      debug:
        description: 'Enable tmate debugging session'
        required: false
        default: false
        type: boolean
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ inputs.debug }}
    - run: ${{ github.event.inputs.command }}
    env:
      GIT_COMMITTER_NAME: GitHub Actions Shell
      GIT_AUTHOR_NAME: GitHub Actions Shell
      EMAIL: github-actions[bot]@users.noreply.github.com
